acc_kwargs:
  task: binary
aucroc_kwargs:
  task: binary
block: basic
block_inplanes:
- 64
- 128
- 256
- 512
feed_forward: true
in_ch: 1
layers:
- 3
- 4
- 6
- 3
loss: !!python/name:torch.nn.modules.loss.BCEWithLogitsLoss ''
loss_kwargs: {}
lr_scheduler: null
lr_scheduler_kwargs: {}
optimizer: !!python/name:torch.optim.adamw.AdamW ''
optimizer_kwargs:
  lr: 0.0001
out_ch: 1
spatial_dims: 3
